// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: model/protobuf.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtobufEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields []*ProtobufEnumItem `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ProtobufEnum) Reset() {
	*x = ProtobufEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufEnum) ProtoMessage() {}

func (x *ProtobufEnum) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufEnum.ProtoReflect.Descriptor instead.
func (*ProtobufEnum) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *ProtobufEnum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtobufEnum) GetFields() []*ProtobufEnumItem {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProtobufEnumItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProtobufEnumItem) Reset() {
	*x = ProtobufEnumItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufEnumItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufEnumItem) ProtoMessage() {}

func (x *ProtobufEnumItem) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufEnumItem.ProtoReflect.Descriptor instead.
func (*ProtobufEnumItem) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *ProtobufEnumItem) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProtobufEnumItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProtobufMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields []*ProtobufMessageField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ProtobufMessage) Reset() {
	*x = ProtobufMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufMessage) ProtoMessage() {}

func (x *ProtobufMessage) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufMessage.ProtoReflect.Descriptor instead.
func (*ProtobufMessage) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *ProtobufMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtobufMessage) GetFields() []*ProtobufMessageField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProtobufMessageBasicField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeName string `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
}

func (x *ProtobufMessageBasicField) Reset() {
	*x = ProtobufMessageBasicField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufMessageBasicField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufMessageBasicField) ProtoMessage() {}

func (x *ProtobufMessageBasicField) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufMessageBasicField.ProtoReflect.Descriptor instead.
func (*ProtobufMessageBasicField) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *ProtobufMessageBasicField) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProtobufMessageBasicField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtobufMessageBasicField) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type ProtobufMessageField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Field:
	//
	//	*ProtobufMessageField_BasicField
	//	*ProtobufMessageField_RepeatedField
	//	*ProtobufMessageField_MapField
	//	*ProtobufMessageField_OneofField
	Field isProtobufMessageField_Field `protobuf_oneof:"field"`
}

func (x *ProtobufMessageField) Reset() {
	*x = ProtobufMessageField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufMessageField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufMessageField) ProtoMessage() {}

func (x *ProtobufMessageField) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufMessageField.ProtoReflect.Descriptor instead.
func (*ProtobufMessageField) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{4}
}

func (m *ProtobufMessageField) GetField() isProtobufMessageField_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (x *ProtobufMessageField) GetBasicField() *ProtobufMessageBasicField {
	if x, ok := x.GetField().(*ProtobufMessageField_BasicField); ok {
		return x.BasicField
	}
	return nil
}

func (x *ProtobufMessageField) GetRepeatedField() *ProtobufMessageRepeatedField {
	if x, ok := x.GetField().(*ProtobufMessageField_RepeatedField); ok {
		return x.RepeatedField
	}
	return nil
}

func (x *ProtobufMessageField) GetMapField() *ProtobufMessageMapField {
	if x, ok := x.GetField().(*ProtobufMessageField_MapField); ok {
		return x.MapField
	}
	return nil
}

func (x *ProtobufMessageField) GetOneofField() *ProtobufMessageOneofField {
	if x, ok := x.GetField().(*ProtobufMessageField_OneofField); ok {
		return x.OneofField
	}
	return nil
}

type isProtobufMessageField_Field interface {
	isProtobufMessageField_Field()
}

type ProtobufMessageField_BasicField struct {
	BasicField *ProtobufMessageBasicField `protobuf:"bytes,1,opt,name=basic_field,json=basicField,proto3,oneof"`
}

type ProtobufMessageField_RepeatedField struct {
	RepeatedField *ProtobufMessageRepeatedField `protobuf:"bytes,2,opt,name=repeated_field,json=repeatedField,proto3,oneof"`
}

type ProtobufMessageField_MapField struct {
	MapField *ProtobufMessageMapField `protobuf:"bytes,3,opt,name=map_field,json=mapField,proto3,oneof"`
}

type ProtobufMessageField_OneofField struct {
	OneofField *ProtobufMessageOneofField `protobuf:"bytes,4,opt,name=oneof_field,json=oneofField,proto3,oneof"`
}

func (*ProtobufMessageField_BasicField) isProtobufMessageField_Field() {}

func (*ProtobufMessageField_RepeatedField) isProtobufMessageField_Field() {}

func (*ProtobufMessageField_MapField) isProtobufMessageField_Field() {}

func (*ProtobufMessageField_OneofField) isProtobufMessageField_Field() {}

type ProtobufMessageMapField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index         int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeyTypeName   string `protobuf:"bytes,3,opt,name=key_type_name,json=keyTypeName,proto3" json:"key_type_name,omitempty"`
	ValueTypeName string `protobuf:"bytes,4,opt,name=value_type_name,json=valueTypeName,proto3" json:"value_type_name,omitempty"`
}

func (x *ProtobufMessageMapField) Reset() {
	*x = ProtobufMessageMapField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufMessageMapField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufMessageMapField) ProtoMessage() {}

func (x *ProtobufMessageMapField) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufMessageMapField.ProtoReflect.Descriptor instead.
func (*ProtobufMessageMapField) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{5}
}

func (x *ProtobufMessageMapField) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProtobufMessageMapField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtobufMessageMapField) GetKeyTypeName() string {
	if x != nil {
		return x.KeyTypeName
	}
	return ""
}

func (x *ProtobufMessageMapField) GetValueTypeName() string {
	if x != nil {
		return x.ValueTypeName
	}
	return ""
}

type ProtobufMessageOneofField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields []*ProtobufMessageField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ProtobufMessageOneofField) Reset() {
	*x = ProtobufMessageOneofField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufMessageOneofField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufMessageOneofField) ProtoMessage() {}

func (x *ProtobufMessageOneofField) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufMessageOneofField.ProtoReflect.Descriptor instead.
func (*ProtobufMessageOneofField) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{6}
}

func (x *ProtobufMessageOneofField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtobufMessageOneofField) GetFields() []*ProtobufMessageField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProtobufMessageRepeatedField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeName string `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
}

func (x *ProtobufMessageRepeatedField) Reset() {
	*x = ProtobufMessageRepeatedField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufMessageRepeatedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufMessageRepeatedField) ProtoMessage() {}

func (x *ProtobufMessageRepeatedField) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufMessageRepeatedField.ProtoReflect.Descriptor instead.
func (*ProtobufMessageRepeatedField) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{7}
}

func (x *ProtobufMessageRepeatedField) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProtobufMessageRepeatedField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtobufMessageRepeatedField) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type ProtobufSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package   string          `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Types     []*ProtobufType `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	GoPackage string          `protobuf:"bytes,3,opt,name=go_package,json=goPackage,proto3" json:"go_package,omitempty"`
}

func (x *ProtobufSchema) Reset() {
	*x = ProtobufSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufSchema) ProtoMessage() {}

func (x *ProtobufSchema) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufSchema.ProtoReflect.Descriptor instead.
func (*ProtobufSchema) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{8}
}

func (x *ProtobufSchema) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ProtobufSchema) GetTypes() []*ProtobufType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ProtobufSchema) GetGoPackage() string {
	if x != nil {
		return x.GoPackage
	}
	return ""
}

type ProtobufType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*ProtobufType_Message
	//	*ProtobufType_Enum
	Type isProtobufType_Type `protobuf_oneof:"type"`
}

func (x *ProtobufType) Reset() {
	*x = ProtobufType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_protobuf_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtobufType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtobufType) ProtoMessage() {}

func (x *ProtobufType) ProtoReflect() protoreflect.Message {
	mi := &file_model_protobuf_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtobufType.ProtoReflect.Descriptor instead.
func (*ProtobufType) Descriptor() ([]byte, []int) {
	return file_model_protobuf_proto_rawDescGZIP(), []int{9}
}

func (m *ProtobufType) GetType() isProtobufType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ProtobufType) GetMessage() *ProtobufMessage {
	if x, ok := x.GetType().(*ProtobufType_Message); ok {
		return x.Message
	}
	return nil
}

func (x *ProtobufType) GetEnum() *ProtobufEnum {
	if x, ok := x.GetType().(*ProtobufType_Enum); ok {
		return x.Enum
	}
	return nil
}

type isProtobufType_Type interface {
	isProtobufType_Type()
}

type ProtobufType_Message struct {
	Message *ProtobufMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ProtobufType_Enum struct {
	Enum *ProtobufEnum `protobuf:"bytes,2,opt,name=enum,proto3,oneof"`
}

func (*ProtobufType_Message) isProtobufType_Type() {}

func (*ProtobufType_Enum) isProtobufType_Type() {}

var File_model_protobuf_proto protoreflect.FileDescriptor

var file_model_protobuf_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x53, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x45, 0x6e, 0x75, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x45, 0x6e,
	0x75, 0x6d, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x5a, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x62, 0x0a, 0x19,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0xb6, 0x02, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x43, 0x0a, 0x0b, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x61, 0x73, 0x69, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x48, 0x00, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x69, 0x63, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x4c,
	0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3d, 0x0a, 0x09,
	0x6d, 0x61, 0x70, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x48,
	0x00, 0x52, 0x08, 0x6d, 0x61, 0x70, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x43, 0x0a, 0x0b, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x42, 0x07, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x17, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x70,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0d, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x64, 0x0a, 0x19, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x6e,
	0x65, 0x6f, 0x66, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x22, 0x65, 0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x74, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x75,
	0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x45, 0x6e, 0x75, 0x6d, 0x48, 0x00, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x42, 0x06, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6a, 0x77, 0x61, 0x6c, 0x74, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_model_protobuf_proto_rawDescOnce sync.Once
	file_model_protobuf_proto_rawDescData = file_model_protobuf_proto_rawDesc
)

func file_model_protobuf_proto_rawDescGZIP() []byte {
	file_model_protobuf_proto_rawDescOnce.Do(func() {
		file_model_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_protobuf_proto_rawDescData)
	})
	return file_model_protobuf_proto_rawDescData
}

var file_model_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_model_protobuf_proto_goTypes = []interface{}{
	(*ProtobufEnum)(nil),                 // 0: model.ProtobufEnum
	(*ProtobufEnumItem)(nil),             // 1: model.ProtobufEnumItem
	(*ProtobufMessage)(nil),              // 2: model.ProtobufMessage
	(*ProtobufMessageBasicField)(nil),    // 3: model.ProtobufMessageBasicField
	(*ProtobufMessageField)(nil),         // 4: model.ProtobufMessageField
	(*ProtobufMessageMapField)(nil),      // 5: model.ProtobufMessageMapField
	(*ProtobufMessageOneofField)(nil),    // 6: model.ProtobufMessageOneofField
	(*ProtobufMessageRepeatedField)(nil), // 7: model.ProtobufMessageRepeatedField
	(*ProtobufSchema)(nil),               // 8: model.ProtobufSchema
	(*ProtobufType)(nil),                 // 9: model.ProtobufType
}
var file_model_protobuf_proto_depIdxs = []int32{
	1,  // 0: model.ProtobufEnum.fields:type_name -> model.ProtobufEnumItem
	4,  // 1: model.ProtobufMessage.fields:type_name -> model.ProtobufMessageField
	3,  // 2: model.ProtobufMessageField.basic_field:type_name -> model.ProtobufMessageBasicField
	7,  // 3: model.ProtobufMessageField.repeated_field:type_name -> model.ProtobufMessageRepeatedField
	5,  // 4: model.ProtobufMessageField.map_field:type_name -> model.ProtobufMessageMapField
	6,  // 5: model.ProtobufMessageField.oneof_field:type_name -> model.ProtobufMessageOneofField
	4,  // 6: model.ProtobufMessageOneofField.fields:type_name -> model.ProtobufMessageField
	9,  // 7: model.ProtobufSchema.types:type_name -> model.ProtobufType
	2,  // 8: model.ProtobufType.message:type_name -> model.ProtobufMessage
	0,  // 9: model.ProtobufType.enum:type_name -> model.ProtobufEnum
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_model_protobuf_proto_init() }
func file_model_protobuf_proto_init() {
	if File_model_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufEnumItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufMessageBasicField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufMessageField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufMessageMapField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufMessageOneofField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufMessageRepeatedField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_protobuf_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtobufType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_model_protobuf_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*ProtobufMessageField_BasicField)(nil),
		(*ProtobufMessageField_RepeatedField)(nil),
		(*ProtobufMessageField_MapField)(nil),
		(*ProtobufMessageField_OneofField)(nil),
	}
	file_model_protobuf_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*ProtobufType_Message)(nil),
		(*ProtobufType_Enum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_protobuf_proto_goTypes,
		DependencyIndexes: file_model_protobuf_proto_depIdxs,
		MessageInfos:      file_model_protobuf_proto_msgTypes,
	}.Build()
	File_model_protobuf_proto = out.File
	file_model_protobuf_proto_rawDesc = nil
	file_model_protobuf_proto_goTypes = nil
	file_model_protobuf_proto_depIdxs = nil
}
